### PR TITLE
Added the possibility to specify the package names

### PR DESCRIPTION
**Pull request by sugarlosses**
This will update the compatibility to be used in Debian 8.0 (or possibly others) in order to use specific versions of the Python packages

### CODE REVIEW

**Comment by llopezsugar** [comment]
@justindowning Please take a look on this proposal, in that way we can use different packages (even outside of the supported distributions).

**Comment by justindowning** [comment]
@llopezsugar Good start!

Can you adjust this so the deps classes reference `awscli::pkg_dev' and `awscli::pkg_pip` instead of the params class? Next, you can remove the if/else in params and just stick with the osfamily defaults. Then, you can set the `awscli::pkg_dev` to `awscli::params::pkg_dev`. This way, it doesn't break backwards compatibility, always gets a default name, and can be overriden by the user. You can see an example of this in another puppet module I support, [puppet-statsd](https://github.com/justindowning/puppet-statsd/blob/master/manifests/init.pp).

**Comment by llopezsugar** [comment]
@justindowning As requested I've refactored with the inheritance from awscli::params :-)

Please let me know if there's another thing I can add... I do believe that there can be another round of refactoring by parameterising the installation part on the *deps* classes, in that way you will end up only with one class specific for installation and getting the necessary values from the params class. (I just didn't wanted to do so drastic changes ;-))

**Comment by justindowning** [comment]
@sugarlosses Ack! This PR seems to have totally slipped my radar! Apologies!

From what I see, this looks good -- and I agree with your suggestion to further simplify things. Feel free to submit another PR for that. I promise I'll try to be more responsive this time! :green_heart:

**Pull request merged**
